"""
github_handler.py
-------------------
Handles all Git + GitHub operations: cloning the repo, writing the fix
to disk, committing on a new branch, pushing, and opening a Pull
Request via the GitHub REST API (through PyGithub).
"""

import os
import shutil
import subprocess
import tempfile
import time
from github import Github, Auth


def clone_repo(repo_full_name: str, token: str) -> str:
    """Clones repo into a temp dir using an authenticated HTTPS URL. Returns local path."""
    tmp_dir = tempfile.mkdtemp(prefix="codeautopsy_")
    clone_url = f"https://x-access-token:{token}@github.com/{repo_full_name}.git"
    subprocess.run(
        ["git", "clone", "--depth", "1", clone_url, tmp_dir],
        check=True, capture_output=True, text=True,
    )
    return tmp_dir


def write_fix(repo_path: str, file_path: str, new_content: str):
    """Overwrites the target file with the AI-generated fix."""
    full_path = os.path.join(repo_path, file_path) if not os.path.isabs(file_path) else file_path
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(new_content)


def commit_and_push(repo_path: str, branch_name: str, commit_message: str, token: str, repo_full_name: str):
    run = lambda cmd: subprocess.run(cmd, cwd=repo_path, check=True, capture_output=True, text=True)
    run(["git", "checkout", "-b", branch_name])
    run(["git", "config", "user.email", "codeautopsy-bot@users.noreply.github.com"])
    run(["git", "config", "user.name", "CodeAutopsy Bot"])
    run(["git", "add", "-A"])
    run(["git", "commit", "-m", commit_message])
    push_url = f"https://x-access-token:{token}@github.com/{repo_full_name}.git"
    run(["git", "push", push_url, branch_name])


def open_pull_request(repo_full_name: str, token: str, branch_name: str,
                       title: str, body: str, base: str = "main"):
    gh = Github(auth=Auth.Token(token))
    repo = gh.get_repo(repo_full_name)
    pr = repo.create_pull(title=title, body=body, head=branch_name, base=base)
    return pr.html_url


def run_full_pipeline(repo_full_name: str, token: str, file_path: str,
                       fixed_content: str, pr_title: str, pr_body: str, base: str = "main"):
    """
    End-to-end: clone -> write fix -> branch -> commit -> push -> open PR.
    Returns the PR URL. Cleans up the temp checkout afterward.
    """
    repo_path = clone_repo(repo_full_name, token)
    try:
        write_fix(repo_path, file_path, fixed_content)
        branch_name = f"codeautopsy/fix-{int(time.time())}"
        commit_and_push(
            repo_path, branch_name,
            commit_message=f"{pr_title}\n\nAuto-generated by CodeAutopsy",
            token=token, repo_full_name=repo_full_name,
        )
        pr_url = open_pull_request(repo_full_name, token, branch_name, pr_title, pr_body, base)
        return pr_url
    finally:
        shutil.rmtree(repo_path, ignore_errors=True)
